### ISSUE TITLE
Unable to create speedrum kit

### ISSUE THREAD

**Issue by spectromas** [porzione/wavescan#2]
Just trying this for the first time and when I'm getting an error that I'm not sure how to solve. Speedrum says that the resultant kit is invalid or unsupported. 
```

./wavescan -d '/home/me/Music Production/Samples/Drums/-Full Kits/Autodafe - Mega Drum Machines Collection/Acetone_Rhythm-Ace/' --speedkit -D > '/home/me/Music Production/Presets & Banks/Speedrum Kits/Acetone_Rhythm-Ace.speedkit'
guess PERC2.WAV is .*chin(a|e).+ 52 Chinese Cymbal
guess PERC1.WAV is .*chin(a|e).+ 52 Chinese Cymbal
guess PERC7.WAV is .*chin(a|e).+ 52 Chinese Cymbal
guess KICK3.WAV is .*(kick|kik|BassDrum).+ 36 Kick 1
guess PERC4.WAV is .*chin(a|e).+ 52 Chinese Cymbal
guess SNARE1.WAV is .*snare.+ 38 Snare
guess KICK1.WAV is .*(kick|kik|BassDrum).+ 36 Kick 1
guess HHCL.WAV is .*(CHH|HHC|Hat.?c|HH.*c~/Music/SFZ/5pin_DrumKit.sfzl|Cl.*Hat|\WCH).+ 42 Closed HH
guess CLAVE.WAV is .*chin(a|e).+ 52 Chinese Cymbal
guess PERC5.WAV is .*chin(a|e).+ 52 Chinese Cymbal
guess SNARE2.WAV is .*snare.+ 38 Snare
guess PERC3.WAV is .*chin(a|e).+ 52 Chinese Cymbal
guess PERC6.WAV is .*chin(a|e).+ 52 Chinese Cymbal
guess SNARE3.WAV is .*snare.+ 38 Snare
guess HHOP.WAV is .*(OHH|HHO|Hat.*Op|HH.*Op|Op.*Hat|Op.*HH|\WOH).+ 46 Open HH
guess KICK2.WAV is .*(kick|kik|BassDrum).+ 36 Kick 1
Traceback (most recent call last):
  File "./wavescan", line 103, in <module>
    bank.build()
  File "/home/me/.git_repos/wavescan/libspeedrum.py", line 110, in build
    self.build_speedkit()
  File "/home/me/.git_repos/wavescan/libspeedrum.py", line 215, in build_speedkit
    ET.indent(self.xml_root, space="\t", level=0)
AttributeError: module 'xml.etree.ElementTree' has no attribute 'indent'
```

python -V
Python 3.8.10

I think not being python 3.9 might be causing the problem. I have it installed but it seems 3.8 is still the default.

**Comment by spectromas** [comment]
Solved this with this - https://askubuntu.com/questions/1347748/how-to-install-latest-version-of-python-3-9-5-on-ubuntu-20-04
